name: flinq
version: 1.0.0
homepage: https://github.com/marchdev-tk/flinq
description: Extended capabilities for collections. It's a bunch of shortcuts to avoid unnecesary boilerplate work with collections.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.9.4
