name: build

on:
  push:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: pub get
      
    - name: Run tests
      run: pub run test
      
#     - name: Coveralls
#       uses: coverallsapp/github-action@v1.0.1
#       with:
#         github-token: ${{ secrets.GITHUB_TOKEN }}
