name: build

on:
  push:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pub get

    - name: Run tests
      run: pub run test

    - name: Activate coverage
      run: pub global activate coverage

    - name: Collect coverage
      run: dart --disable-service-auth-codes --enable-vm-service=8111 --pause-isolates-on-exit test/flinq_test.dart & nohup pub global run coverage:collect_coverage --port=8111 --out=coverage.json --wait-paused --resume-isolates

    - name: Convert coverage
      run: pub global run coverage:format_coverage --lcov --in=coverage.json --out=lcov.info --packages=.packages --report-on=lib

    - name: Send coverage to Codecov.io
      run: bash <(curl -s https://codecov.io/bash) -t b3b3925e-408c-4e5b-9799-5bc6e287af96
